greasemonkey-geocaching-projectgc.user.js
Toggle the Print and Downloads arrow to show the down arrow when the Print and Downloads box is open.
=> Toggle Print and Downloads arrow

greasemonkey-geocaching-projectgc.user.js
=> Changecopy friendly link box positioning slightly

README.md, greasemonkey-geocaching-projectgc.user.js
=> Add famsl support

greasemonkey-geocaching-projectgc.user.js
=> Remove px from 0

README.md, greasemonkey-geocaching-projectgc.user.js
Fixes the known issue by manually applying the missing needed css styles.
=> Fix profile page styling

greasemonkey-geocaching-projectgc.user.js
Display message if cache is locked from being logged. Issue #31 
Updated version to next point release.
=> Add message if cache is locked - Issue #31

greasemonkey-geocaching-projectgc.user.js
Replaces #45 addressing remarks in the comments.
=> Jakuje suppress alerts

greasemonkey-geocaching-projectgc.user.js
Fixes coordinate problem in issue #59
=> Fix for issue #59

greasemonkey-geocaching-projectgc.user.js
Added possibility to change font on personal cache note to monospaced as described in issue #55
=> Enhancement: Added monospace font to personal cache note

greasemonkey-geocaching-projectgc.user.js
Adds link to the users profile page on the username in the to-bar in message center
Fixes #57
=> Enhancement: Add link to users profile page in message center

greasemonkey-geocaching-projectgc.user.js
After:
Known issue: 
- something like `#pgcUserMenuButton:focus, #pgcUserMenuButton:hover { color: #02874d; }` should be needed to have the arrow change color on focus/hover to avoid "polar bears in snow". However, can't get it to work right now :(
=> make the pgc stuff look somewhat sane with updated layout. Fixes #64

greasemonkey-geocaching-projectgc.user.js
Tested also compatibility with GM 3 (Firefox 56) and TP (Chrome)
Resolves #73
=> GM 4 API for Firefox 57 (Tested with Nightly)

greasemonkey-geocaching-projectgc.user.js
This makes the latest logs working for me.
=> unbreak latestLogs (#76)

greasemonkey-geocaching-projectgc.user.js
See: https://project-gc.com/qa/?qa=23015/project-gc-tampermonkey-userscript-broken
=> Updated to support new ID for personal cache notes

greasemonkey-geocaching-projectgc.user.js
Now using monospace while editing PCNs.
=> Updated personal cache note editing font

greasemonkey-geocaching-projectgc.user.js
=> fix decryptHints

greasemonkey-geocaching-projectgc.user.js
Make the setting labels (not only the checkboxes) clickable.
=> Clickable label in the settings

greasemonkey-geocaching-projectgc.user.js
fix #72 
Thanks for the code snippet from the GClh
=> Add weekday of place date

greasemonkey-geocaching-projectgc.user.js
=> PGC header for search map, BML, CO Dashboard

greasemonkey-geocaching-projectgc.user.js
=> fix header when gclh is running

greasemonkey-geocaching-projectgc.user.js
add "@icon" metadata to make it easier to identify the userjs
=> add @icon for easier recognition

greasemonkey-geocaching-projectgc.user.js
#97
https://github.com/2Abendsegler/GClh/issues/1783
Now the pgc header works also on new header
=> rewrite pgc header

greasemonkey-geocaching-projectgc.user.js
Fixes #109 - lastestLogs; using span instead of div.
=> Fixed #109

greasemonkey-geocaching-projectgc.user.js
Fixed issue #113 and made a few minor wording changes to the settings menu.
=> Fixed #113 

README.md, greasemonkey-geocaching-projectgc.user.js
version number 2.3.15 -> 2.3.16
Finish updates from Rick (Dr.Pflug)
README updates.  Lots of changes to WIKI.
=> 2022-09-03 Updates

greasemonkey-geocaching-projectgc.user.js
=> version 2.3.16 won't load #131

greasemonkey-geocaching-projectgc.user.js
Incorporates fixes for #133 (rteitelman).
Adds fixes for several indentation issues and lint based errors.  Fixing a handful of syntax issues.   Fixes use of comma instead of semi-colon. Clean-up spacing and comments.
=> Fixes #133 Patch to 2.3.18

greasemonkey-geocaching-projectgc.user.js
Reverts magma1447/greasemonkey-geocaching-projectgc#135
It passed all checks, but it will not load.  Reverting.
=> Revert "Fixes #133 Patch to 2.3.18"

greasemonkey-geocaching-projectgc.user.js
@cghove Thank you for pushing 2.3.16 fixes. I reviewed the code, but did not import it into my GreaseMonkey .. so I missed the syntax errors. Ugh. Well that won't happen again!  Thanks again!
@rteitelman
Verified lines added work, and features are working.
=> Fixes #133

greasemonkey-geocaching-projectgc.user.js
fixes #140
Thanks [cghove](https://github.com/cghove)
=> Settings menu reloads page if GClh is installed
